spring.application.name=platos-tipicos-sb-api

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/platos-tipicos?prepareThreshold=0
spring.datasource.username=postgres.nobcvbhvsruqdufkyvtp
spring.datasource.password=platosTipicosCO
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

